//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ıs_takip_proje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cagrilar
    {
        public int Id { get; set; }
        public Nullable<int> CagriFirma { get; set; }
        public string Konu { get; set; }
        public string Aciklama { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Tbl_Firmalar Tbl_Firmalar { get; set; }
    }
}
